services:
  nexasphere-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexasphere-web
    restart: always
    ports:
      - "8008:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

