services:
  nexasphere-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexasphere-web
    restart: always
    ports:
      - "8008:3000" # Exposing port 8008 for Nginx Proxy Manager
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
